### ISSUE TITLE
Creating a fakeServer?

### ISSUE THREAD

**Issue by ayxos** [elliotf/mocha-sinon#13]
I want to return a mock when my code calls "/test" GET endpoint. Is there any way?

**Comment by elliotf** [comment]
@ayxos I'd suggest two things:

1) I use nock ( https://github.com/node-nock/nock )  for my projects, since most of what I do is server side.  I set nock up in my test helper:
```javascript
var nock            = require('nock');
nock.enableNetConnect(/^127.0.0.1/);

beforeEach(function() {
  nock.cleanAll(); // remove nock mocks between every scenario
});
```

Then in my test:
```javascript
describe('something', function() {
  beforeEach(function() {
    nock(some_host)
      .get('/some/path')
      .reply(200, '{"fake":"response here"}')
  });

  // in reality different contexts would have different responses, 4xx, 3xx, etc.
});
```

2) I've not used it, but maybe try using sinon's built-in fake http server.  If you're using mocha-sinon, you'd do something like ```javascript
beforeEach(function() {
  this.sinon.useFakeXMLHttpRequest();

  // do things with the fake server : http://sinonjs.org/releases/v2.1.0/fake-xhr-and-server/
});
```

Is that what you had in mind?
